name: Deploy com GMUD ClickUp

on:
  workflow_dispatch:
    inputs:
      casa:
        description: 'Nome da casa (ex: br4bet)'
        required: true
        type: string
      ambiente:
        description: 'Ambiente (dev|hml|prd)'
        required: true
        type: string
        default: 'hml'

env:
  LIST_ID: '901321558663'

jobs:
  gmud-gate:
    runs-on: ubuntu-latest
    outputs:
      task_id: ${{ steps.gate.outputs.task_id }}
      approved: ${{ steps.gate.outputs.approved }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ClickUp GMUD Gate
        id: gate
        uses: ./.github/actions/clickup-gmud
        with:
          clickup_token: ${{ secrets.CLICKUP_TOKEN }}
          list_id: ${{ env.LIST_ID }}
          casa: ${{ inputs.casa }}
          ambiente: ${{ inputs.ambiente }}
          usuario: ${{ github.actor }}
          pipeline_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          timeout_minutes: '60'
          poll_interval_seconds: '30'

  deploy:
    runs-on: ubuntu-latest
    needs: gmud-gate
    if: ${{ success() }}
    steps:
      - name: Deploy
        run: |
          echo "🚀 Iniciando deploy de ${{ inputs.casa }} para ${{ inputs.ambiente }}"
          # Aqui você coloca seu script de deploy real
          # ./deploy.sh ${{ inputs.casa }} ${{ inputs.ambiente }}

  notify-complete:
    runs-on: ubuntu-latest
    needs: [gmud-gate, deploy]
    if: ${{ always() }}
    steps:
      - name: Notificar conclusão
        run: |
          if [ "${{ needs.deploy.result }}" == "success" ]; then
            echo "✅ Deploy concluído com sucesso"
          else
            echo "❌ Deploy falhou"
          fi
